root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/gurayme"
  cmd = "templ generate && GO111MODULE=on CGO_ENABLED=0 go build -o ./tmp/gurayme ./cmd/server/main.go"
  delay = 1000
  exclude_dir = [".parcel-cache", "tests", "tmp", "vendor", "testdata", "node_modules", "public", "static", "dist", "build", "bin"]
  exclude_file = []
  exclude_regex = ["_test\\.go", "_templ\\.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "templ", "html", "yaml", "yml", "toml"]
  include_file = []
  kill_delay = 1000
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = ["bun run build"]
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = true

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
  keep_scroll = true
