version: "3.8"
services:
  mysql:
    image: mysql:8.0-bullseye
    container_name: mysql
    restart: always
    command: mysqld --user=root --default-authentication-plugin=mysql_native_password --init-file=/docker-entrypoint-initdb.d/dump.sql --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql-mode=""
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      - default
    volumes:
      - mysql_data:/var/lib/mysql
      - ./build/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  go:
    container_name: gurayme
    restart: always
    build:
      context: ./build
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - ${PORT}:80
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      PORT: ${PORT}
    stdin_open: true
    tty: true
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - ${PHPMYADMIN_PORT}:80
    restart: always
    environment:
      PMA_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PHPMYADMIN_PORT: ${PHPMYADMIN_PORT}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - default

volumes:
  mysql_data:
