// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package layout

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Footer() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<footer class=\"flex flex-col justify-between items-center text-center align-bottom m-2\"><section class=\"\"><copyright xmlns:dct=\"http://purl.org/dc/terms/\" class=\"flex flex-wrap items-center hover:underline text-sm font-medium font-mono text-black dark:text-white hover:text-green-600 dark:hover:text-green-500\" href=\"http://purl.org/dc/dcmitype/InteractiveResource\" property=\"dct:title\" rel=\"dct:type\" id=\"copyright\"><a target=\"_top\" xmlns:cc=\"http://creativecommons.org/ns#\" href=\"http://guray.me/\" property=\"cc:attributionName\" rel=\"cc:attributionURL\"><strong><p id=\"datetime\"></p></strong></a></copyright></section></footer><script type=\"text/javascript\" defer nonce=\"csp-nonce\" id=\"csp-nonce\">\n\tvar d = new Date();\n\tvar y = d.getFullYear();\n\tlet datetime = y.toString();\n\tdocument.getElementById(\"datetime\").innerHTML = \" © \" + datetime + \" guray.me\";\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
